import 'dart:math';

String generateExcuse() {
  final animals = [
    "Lion",
    "Tiger",
    "Elephant",
    "Giraffe",
    "Zebra",
    "Kangaroo",
    "Koala",
    "Panda",
    "Gorilla",
    "Hippopotamus",
    "Rhino",
    "Cheetah",
    "Leopard",
    "Wolf",
    "Fox",
    "Bear",
    "Penguin",
    "Polar Bear",
    "Dolphin",
    "Whale",
    "Shark",
    "Octopus",
    "Seal",
    "Otter",
    "Sloth",
    "Monkey",
    "Chimpanzee",
    "Orangutan",
    "Gibbon",
    "Baboon",
    "Tamarin",
    "Gazelle",
    "Deer",
    "Antelope",
    "Buffalo",
    "Moose",
    "Caribou",
    "Horse",
    "Donkey",
    "Zebra",
    "Camel",
    "Llama",
    "Alpaca",
    "Sheep",
    "Goat",
    "Cow",
    "Pig",
    "Dog",
    "Cat",
    "Rabbit",
  ];


  final famousPeople = [
    "Steve Wozniak",
    "Emma Watson",
    "Albert Einstein",
    "Oprah Winfrey",
    "Leonardo da Vinci",
    "Stephen Hawking",
    "Nelson Mandela",
    "Malala Yousafzai",
    "Martin Luther King Jr.",
    "Mahatma Gandhi",
    "Walt Disney",
    "Marie Curie",
    "Isaac Newton",
    "Coco Chanel",
    "Abraham Lincoln",
    "Elon Musk",
    "Bill Gates",
    "Steve Jobs",
    "JK Rowling",
    "Michael Jackson",
    "Vincent van Gogh",
    "Pablo Picasso",
    "Marilyn Monroe",
    "Audrey Hepburn",
    "Barack Obama",
    "Queen Elizabeth II",
    "Charles Darwin",
    "Amelia Earhart",
    "Rosa Parks",
    "Mother Teresa",
    "Frida Kahlo",
    "Nikola Tesla",
    "Mark Zuckerberg",
    "Stephen King",
    "Aristotle",
    "Helen Keller",
    "Elvis Presley",
    "Beyoncé",
    "David Bowie",
    "Leonardo DiCaprio",
    "Madonna",
    "Tom Hanks",
    "JK Rowling",
    "George Washington",
    "Anne Frank",
    "Mozart",
    "Prince",
    "Bob Dylan",
    "Bruce Lee",
    "Michael Jordan",
  ];

  final intro = [
    "Sorry I can't come,",
    "Please forgive my absence,",
    "This is going to sound crazy but",
    "Get this:",
    "I can't go because",
    "I know you're going to hate me but",
    "I was minding my own business and",
    "I feel terrible but",
    "I regretfully cannot attend,",
    "This is going to sound like an excuse but",
    "I didn't expect this to happen but",
    "It's unbelievable but",
    "I swear I'm not making this up but",
    "I couldn't believe it myself but",
    "I'm really sorry but",
    "I never thought this would happen but",
    "I'm embarrassed to say but",
    "I'm in shock but",
    "I couldn't make this up if I tried but",
    "I know you won't believe me but",
    "I'm completely baffled but",
    "Believe it or not,",
    "I wish I could come but",
    "You'll think I'm joking but",
    "I'm at a loss for words but",
    "This is beyond my control but",
    "I can't even begin to explain but",
  ];

  final scapegoat = [
    "#",
    "?",
    "my nephew",
    "the ghost of Hitler",
    "the Pope",
    "my ex",
    "a high school marching band",
    "a sad clown",
    "the kid from Air Bud",
    "a professional cricket team",
    "my Tinder date",
    "a group of aliens",
    "a talking dolphin",
    "a time-traveling unicorn",
    "a troupe of dancing penguins",
    "a colony of ants",
    "a psychic banana",
    "a mischievous leprechaun",
    "a sentient robot",
    "a pack of wild llamas",
    "a magical talking tree",
  ];

  final delay = [
    "just shat my bed",
    "died in front of me",
    "won't stop telling me knock knock jokes",
    "is having a nervous breakdown",
    "gave me syphilis",
    "poured lemonade in my gas tank",
    "stabbed me",
    "found my box of human teeth",
    "stole my bicycle",
    "posted my nudes on Instagram",
    "filled my house with balloons",
    "sent me on a wild goose chase",
    "hid my car keys",
    "ate my homework",
    "started a rumor about me",
    "hid my phone charger",
    "ate all the cookies",
    "pranked me with fake lottery tickets",
    "replaced my shampoo with mayonnaise",
    "locked me out of my own house",
    "gave birth to a litter of puppies",
    "put a hex on me",
    "rewrote my will",
    "challenged me to a dance-off",
    "held me hostage in a game of Monopoly",
    "convinced me I was allergic to sunlight",
    "invited me to a séance",
    "told me I was adopted",
    "chased me with a feather boa",
    "knocked over my beehive",
    "dared me to eat a whole jar of pickles",
    "made me believe I was a superhero",
    "taught me how to yodel",
    "introduced me to their imaginary friend",
    "suggested we reenact a scene from Titanic",
    "asked me to join their cult",
    "challenged me to a staring contest",
    "trained me to speak dolphin",
    "tried to sell me a bridge",
    "informed me I was the heir to a fortune",
    "organized a flash mob in my honor",
    "accused me of being a time traveler",
    "convinced me I had a twin",
    "declared me the chosen one",
    "demonstrated their talent for juggling chainsaws",
    "proposed to me on live television",
    "insisted we go on a treasure hunt",
  ];

  final random = Random.secure();

  final introIndex = random.nextInt(intro.length);
  final scapegoatIndex = random.nextInt(scapegoat.length);
  final delayIndex = random.nextInt(delay.length);

  String finalScapegoat = scapegoat[scapegoatIndex];
  if (scapegoatIndex == 0) {
    finalScapegoat = famousPeople[random.nextInt(famousPeople.length)];
  }else if(scapegoatIndex == 1){
    finalScapegoat = "a ${animals[random.nextInt(animals.length)]}";
  }

  final excuse = '${intro[introIndex]} $finalScapegoat ${delay[delayIndex]}.';
  return excuse;
}